CC = gcc
CFLAGS = -Wall -Wextra -std=c11

TARGET = Variables
SRC = Variables.c

ARRAYS_TARGET = Arrays
ARRAYS_SRC = Arrays.c

DATATYPES_TARGET = DataTypes
DATATYPES_SRC = DataTypes.c

PRINTF_TARGET = Printf
PRINTF_SRC = Printf.c

NUMBERS_TARGET = Numbers
NUMBERS_SRC = Numbers.c

CONSTANTS_TARGET = Constants
CONSTANTS_SRC = Constants.c

USERINPUT_TARGET = UserInput
USERINPUT_SRC = UserInput.c

FUNCTIONS_TARGET = Functions
FUNCTIONS_SRC = Functions.c

IFSTATEMENTS_TARGET = ifStatements
IFSTATEMENTS_SRC = ifStatements.c

MEMORYADDRESSES_TARGET = MemoryAddresses
MEMORYADDRESSES_SRC = MemoryAddresses.c

FILES_TARGET = files
FILES_SRC = files.c

PTHREADS_TARGET = pthreads
PTHREADS_SRC = pthreads.c

all: $(TARGET) $(ARRAYS_TARGET) $(DATATYPES_TARGET) $(PRINTF_TARGET) $(NUMBERS_TARGET) $(CONSTANTS_TARGET) $(USERINPUT_TARGET) $(FUNCTIONS_TARGET) $(IFSTATEMENTS_TARGET) $(MEMORYADDRESSES_TARGET) $(FILES_TARGET) $(PTHREADS_TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

$(ARRAYS_TARGET): $(ARRAYS_SRC)
	$(CC) $(CFLAGS) -o $(ARRAYS_TARGET) $(ARRAYS_SRC)

$(DATATYPES_TARGET): $(DATATYPES_SRC)
	$(CC) $(CFLAGS) -o $(DATATYPES_TARGET) $(DATATYPES_SRC)

$(PRINTF_TARGET): $(PRINTF_SRC)
	$(CC) $(CFLAGS) -o $(PRINTF_TARGET) $(PRINTF_SRC)

$(NUMBERS_TARGET): $(NUMBERS_SRC)
	$(CC) $(CFLAGS) -o $(NUMBERS_TARGET) $(NUMBERS_SRC)

$(CONSTANTS_TARGET): $(CONSTANTS_SRC)
	$(CC) $(CFLAGS) -o $(CONSTANTS_TARGET) $(CONSTANTS_SRC)

$(USERINPUT_TARGET): $(USERINPUT_SRC)
	$(CC) $(CFLAGS) -o $(USERINPUT_TARGET) $(USERINPUT_SRC)

$(FUNCTIONS_TARGET): $(FUNCTIONS_SRC)
	$(CC) $(CFLAGS) -o $(FUNCTIONS_TARGET) $(FUNCTIONS_SRC)

$(IFSTATEMENTS_TARGET): $(IFSTATEMENTS_SRC)
	$(CC) $(CFLAGS) -o $(IFSTATEMENTS_TARGET) $(IFSTATEMENTS_SRC)

$(MEMORYADDRESSES_TARGET): $(MEMORYADDRESSES_SRC)
	$(CC) $(CFLAGS) -o $(MEMORYADDRESSES_TARGET) $(MEMORYADDRESSES_SRC)

$(FILES_TARGET): $(FILES_SRC)
	$(CC) $(CFLAGS) -o $(FILES_TARGET) $(FILES_SRC)

$(PTHREADS_TARGET): $(PTHREADS_SRC)
	$(CC) $(CFLAGS) -o $(PTHREADS_TARGET) $(PTHREADS_SRC) -lpthread

clean:
	rm -f $(TARGET) $(ARRAYS_TARGET) $(DATATYPES_TARGET) $(PRINTF_TARGET) $(NUMBERS_TARGET) $(CONSTANTS_TARGET) $(USERINPUT_TARGET) $(FUNCTIONS_TARGET) $(IFSTATEMENTS_TARGET) $(MEMORYADDRESSES_TARGET) $(FILES_TARGET) $(PTHREADS_TARGET)

.PHONY: all clean
